@server=http://localhost:4004
@username=alice
@password=


### Customers
# @name Customers_GET
GET {{server}}/main/Customers?$select=name&$expand=orders($expand=nf)
Authorization: Basic {{username}}:{{password}}

// count, expand, select, orderby, skip, top
